import { Router } from 'express';
import { CreateProduct, DeleteProduct, GetAllProduct, GetProductById, updateProduct, } from '../controllers/product.js';
// import { checkAuth } from '../middleware/checkAuth.js';
const Router_Product = Router();
Router_Product.post('/products', CreateProduct);
Router_Product.get('/products', GetAllProduct);
Router_Product.delete('/products/:id', DeleteProduct);
Router_Product.patch('/products/:id', updateProduct);
Router_Product.get('/products/:id', GetProductById);
export default Router_Product;